---
- name: Install Hubot.
  hosts: all
  become: true
  vars:
    - email: "brady@thewellinspired.com"
    - ssh_user: deploy
    - fail2ban:
        config:
          ignoreip: 127.0.0.1/8
          bantime: 3600
          maxretry: 3
  roles:
    - swap
    - fail2ban
    - ufw
    - common
    - hubot
    - redis
